[package]
name = "dev-test-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"]}
serde_path_to_error = "0.1.20"
regex = "1"
once_cell = "1"

[dependencies.json-osi]
path = ".."


